Repository MoonBaar/moon-baar-backend, pull requests merged in 2025-04, with the labels that each got.

#16 feat: CORS 설정 추가
  .github/workflows/deploy.yml
  src/main/java/com/moonbaar/common/config/SecurityConfig.java
Labels: ✨ Feature

#20 refactor: 행정구역과 카테고리 ID를 지정된 값으로 고정
  docker-files/data-init/get_cultural_events.py
Labels: 🔨 Refactor

#21 refactor: 문화행사 API 응답 필드 개선 및 예외 처리 수정
  src/main/java/com/moonbaar/domain/event/controller/EventController.java
  src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java
  src/main/java/com/moonbaar/domain/event/dto/EventSummaryResponse.java
  src/main/java/com/moonbaar/domain/event/exeption/InvalidEventParamsException.java
  src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java
Labels: 🔨 Refactor

#28 refactor: 행사 검색 시 날짜 필터링 로직 개선
  src/main/java/com/moonbaar/domain/event/repository/EventSpecifications.java
  src/test/java/com/moonbaar/domain/event/repository/CulturalEventRepositoryTest.java
Labels: 🔨 Refactor

#29 feat: 행사 좋아요 API 구현
  src/main/java/com/moonbaar/MoonbaarApplication.java
  src/main/java/com/moonbaar/domain/like/controller/LikeController.java
  src/main/java/com/moonbaar/domain/like/dto/LikeResponse.java
  src/main/java/com/moonbaar/domain/like/entity/LikedEvent.java
  src/main/java/com/moonbaar/domain/like/exception/AlreadyLikedEventException.java
  src/main/java/com/moonbaar/domain/like/exception/LikeErrorCode.java
  src/main/java/com/moonbaar/domain/like/exception/LikeNotFoundException.java
  src/main/java/com/moonbaar/domain/like/repository/LikedEventRepository.java
  src/main/java/com/moonbaar/domain/like/service/LikeService.java
  src/main/java/com/moonbaar/domain/user/entity/User.java
  src/main/java/com/moonbaar/domain/user/exception/UserErrorCode.java
  src/main/java/com/moonbaar/domain/user/exception/UserNotFoundException.java
  src/main/java/com/moonbaar/domain/user/repository/UserRepository.java
  src/test/java/com/moonbaar/domain/like/controller/LikeControllerTest.java
Labels: ✨ Feature

#31 fix: 서비스 메서드 likeEvent 인자 순서 수정
  src/main/java/com/moonbaar/domain/like/controller/LikeController.java
Labels: 🐞 BugFix

#39 feat: 발자국 지도(지도 범위 기반 방문 위치 조회) api 구현
  src/main/java/com/moonbaar/domain/visit/controller/FootprintController.java
  src/main/java/com/moonbaar/domain/visit/dto/FootprintListResponse.java
  src/main/java/com/moonbaar/domain/visit/dto/FootprintRequest.java
  src/main/java/com/moonbaar/domain/visit/dto/FootprintResponse.java
  src/main/java/com/moonbaar/domain/visit/repository/VisitRepository.java
  src/main/java/com/moonbaar/domain/visit/service/FootprintService.java
  src/test/java/com/moonbaar/domain/visit/controller/FootprintControllerTest.java
Labels: ✨ Feature

#46 feat: 사용자 관련 api 구현
  src/main/java/com/moonbaar/common/config/SecurityConfig.java
  src/main/java/com/moonbaar/common/filter/JwtAuthenticationFilter.java
  src/main/java/com/moonbaar/common/oauth/CustomUserDetails.java
  src/main/java/com/moonbaar/common/oauth/service/CustomUserDetailsService.java
  src/main/java/com/moonbaar/domain/like/entity/LikedEvent.java
  src/main/java/com/moonbaar/domain/user/controller/UserController.java
  src/main/java/com/moonbaar/domain/user/dto/UserInfoResponse.java
  src/main/java/com/moonbaar/domain/user/repository/UserRepository.java
  src/main/java/com/moonbaar/domain/user/service/UserService.java
  src/main/java/com/moonbaar/domain/visit/entity/Visit.java
Labels: ✨ Feature

#51 feat: 인증서 추가
  .github/workflows/deploy.yml
  docker-compose.yml
  docker-files/nginx/Dockerfile
  docker-files/nginx/conf/default.conf
  docker-files/nginx/nginx-entrypoint.sh
  docker-files/nginx/nginx.conf.template
  src/main/java/com/moonbaar/common/oauth/handler/OAuth2SuccessHandler.java
  src/main/java/com/moonbaar/domain/user/service/UserService.java
Labels: 🌏 Deploy, ✨ Feature

#52 fix: logout response에 SameSite None 설정 추가
  src/main/java/com/moonbaar/domain/user/service/UserService.java
Labels: 🐞 BugFix

#53 feat: 배지 api 구현
  src/main/java/com/moonbaar/domain/badge/controller/BadgeController.java
  src/main/java/com/moonbaar/domain/badge/dto/BadgeEvaluationContext.java
  src/main/java/com/moonbaar/domain/badge/dto/BadgeListResponse.java
  src/main/java/com/moonbaar/domain/badge/dto/BadgeProgressResponse.java
  src/main/java/com/moonbaar/domain/badge/dto/BadgeResponse.java
  src/main/java/com/moonbaar/domain/badge/dto/UserBadgeListResponse.java
  src/main/java/com/moonbaar/domain/badge/dto/UserBadgeResponse.java
  src/main/java/com/moonbaar/domain/badge/entity/Badge.java
  src/main/java/com/moonbaar/domain/badge/entity/UserBadge.java
  src/main/java/com/moonbaar/domain/badge/enums/BadgeCode.java
  src/main/java/com/moonbaar/domain/badge/enums/BadgeType.java
  src/main/java/com/moonbaar/domain/badge/exception/BadgeErrorCode.java
  src/main/java/com/moonbaar/domain/badge/exception/BadgeNotFoundException.java
  src/main/java/com/moonbaar/domain/badge/repository/BadgeRepository.java
  src/main/java/com/moonbaar/domain/badge/repository/UserBadgeRepository.java
  src/main/java/com/moonbaar/domain/badge/service/BadgeService.java
Labels: ✨ Feature

#55 feat: 행사 상세조회 isLiked, isVisited 값 유저 정보와 연결 및 유저 방문 목록 조회 api 구현
  src/main/java/com/moonbaar/domain/event/controller/EventController.java
  src/main/java/com/moonbaar/domain/event/dto/EventDetailResponse.java
  src/main/java/com/moonbaar/domain/event/service/EventService.java
  src/main/java/com/moonbaar/domain/visit/controller/UserVisitController.java
  src/main/java/com/moonbaar/domain/visit/dto/VisitItemResponse.java
  src/main/java/com/moonbaar/domain/visit/dto/VisitListRequest.java
  src/main/java/com/moonbaar/domain/visit/dto/VisitListResponse.java
  src/main/java/com/moonbaar/domain/visit/repository/VisitRepository.java
  src/main/java/com/moonbaar/domain/visit/service/UserVisitService.java
  src/test/java/com/moonbaar/domain/event/controller/EventControllerTest.java
  src/test/java/com/moonbaar/domain/event/repository/CulturalEventRepositoryTest.java
  src/test/java/com/moonbaar/domain/event/service/EventServiceTest.java
  src/test/java/com/moonbaar/domain/visit/controller/UserVisitControllerTest.java
Labels: ✨ Feature
